### ISSUE TITLE
Don't mention everyone when hereabout is used within a code block

### ISSUE THREAD

**Issue by kylef** [apiaryio/slack-here-bot#3]
Mentions should not be triggered from using code blocks containing herebot.

![screen shot 2015-06-02 at 13 17 01](https://cloud.githubusercontent.com/assets/44164/7946104/a0f14b36-0929-11e5-9bac-52524934d00f.png)

**Comment by abtris** [comment]
@kylef I make some proposal in #1 Can you look into if it's ok for you.

**Comment by abtris** [comment]
Nice, I think we should also add a test for fenced code blocks too:

```
@herebot
```
And perhaps block quotes?

> @herebot test

**Comment by abtris** [comment]
I hope latest version support all this types.

**Comment by kylef** [comment]
Closing issue since it's no longer relevant (slack got has build their own `@here`).
